export const Data={
    teams:[
        {
          id:1,
          meta:{
            name:'Arseenal',
            stadium:'Emirates',
          },
          images:{
            creast:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKctcCFROSk1XIbKw83k4nW4ORklJ9dG7FuA&usqp=CAU',
            stadium:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9eph6jqtuXY4xb0pcLE8cErYeAClzmhIyEw&usqp=CAU'
          },
          players:[
            {
                jerseyNo:1,
                name:'Berned leno',
                position:'Goalkeeper',
                images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0M9R2t13LUu2_8KsX0IeCMOsSy13G0pP1lQ&usqp=CAU',
                nationality:{
                    country:'Germany',
                    nationality:'German'
                },
            },
            {
                jerseyNo:2,
                name:'Ranar Alex Ranarsson',
                position:'Goalkeeper',
                images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7cGfAfns7i2EJJC0OGX7qCNjlp_FjcJ9c3Q&usqp=CAU',
                nationality:{
                    country:'iceland',
                    nationality:'icelandic',
                    logo:'',
                },
            },
          ]
        },
        {
            id:2,
            meta:{
              name:'Arseenal',
              stadium:'Emirates',
            },
            images:{
              creast:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_3Y4S2B1Cr5DzEOKQqNG_nCFuJ0dNMN217g&usqp=CAU',
              stadium:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkRKcJtd1IcGTGct0jcZtP4sdTTHAH4sX9-Q&usqp=CAU'
            },
            players:[
              {
                  jerseyNo:1,
                  name:'Berned leno',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2B1ueE1_2BOLcYnUD5sHLUe7sY2p1QwNZJA&usqp=CAU',
                  nationality:{
                      country:'Germany',
                      nationality:'German',
                      logo:'',
                  },
              },
              {
                  jerseyNo:2,
                  name:'Ranar Alex Ranarsson',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCKhGlKtSmngRkf0ZL-YBDk_m9T40b-qAZBA&usqp=CAU',
                  nationality:{
                      country:'iceland',
                      nationality:'icelandic',
                      logo:'',
                  },
              },
            ]
          },
          {
            id:3,
            meta:{
              name:'Arseenal',
              stadium:'Emirates',
            },
            images:{
              creast:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKctcCFROSk1XIbKw83k4nW4ORklJ9dG7FuA&usqp=CAU',
              stadium:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9eph6jqtuXY4xb0pcLE8cErYeAClzmhIyEw&usqp=CAU'
            },
            players:[
              {
                  jerseyNo:1,
                  name:'Berned leno',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8Jgq4slBYYMQPsNuu-U7GKcAmyE8TtkaJ8w&usqp=CAU',
                  nationality:{
                      country:'Germany',
                      nationality:'German'
                  },
              },
              {
                  jerseyNo:2,
                  name:'Ranar Alex Ranarsson',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN8d0q6pyQQA_wj_Tj18DsIZvJPs6sglVn0GnjKJioQI-fGTnqc7eY-gPwosA5qA0HC38&usqp=CAU',
                  nationality:{
                      country:'iceland',
                      nationality:'icelandic'
                  },
              },
            ]
          },
          {
            id:4,
            meta:{
              name:'Arseenal',
              stadium:'Emirates',
            },
            images:{
              creast:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsfgvGKt8mm88DZkBBxLAQ6a1Qw5wHePsyIQ&usqp=CAU',
              stadium:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9eph6jqtuXY4xb0pcLE8cErYeAClzmhIyEw&usqp=CAU'
            },
            players:[
              {
                  jerseyNo:1,
                  name:'Berned leno',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL1MHS6UAxshg9-2hnW7biblg1uRWX3XRqBA&usqp=CAU',
                  nationality:{
                      country:'Germany',
                      nationality:'German',
                      logo:'',
                  },
              },
              {
                  jerseyNo:2,
                  name:'Ranar Alex Ranarsson',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCKhGlKtSmngRkf0ZL-YBDk_m9T40b-qAZBA&usqp=CAU',
                  nationality:{
                      country:'iceland',
                      nationality:'icelandic',
                      logo:'',
                  },
              },
            ]
          },
          {
            id:5,
            meta:{
              name:'Arseenal',
              stadium:'Emirates',
            },
            images:{
              creast:'https://www.pngwing.com/en/free-png-sgwmx',
              stadium:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMGTTWJPZuPSe3iU4Np283hdNjiLafwbQB2A&usqp=CAU'
            },
            players:[
              {
                  jerseyNo:1,
                  name:'Berned leno',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTRzJhDoiMq8tzh1sB6Aqj69Kxuw6DVHaq2Q&usqp=CAU',
                  nationality:{
                      country:'Germany',
                      nationality:'German',
                      logo:'',
                  },
              },
              {
                  jerseyNo:2,
                  name:'Ranar Alex Ranarsson',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTRzJhDoiMq8tzh1sB6Aqj69Kxuw6DVHaq2Q&usqp=CAU',
                  nationality:{
                      country:'iceland',
                      nationality:'icelandic',
                      logo:'',
                  },
              },
            ]
          },
          {
            id:6,
            meta:{
              name:'Arseenal',
              stadium:'Emirates',
            },
            images:{
              creast:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf2sBmTvk2BfWmL9d1ueMGlu8lrp9vPfZD1w&usqp=CAU',
              stadium:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAZw_dym6Esc6FYlLtJbUXARUTYd4N3OX4xw&usqp=CAU'
            },
            players:[
              {
                  jerseyNo:1,
                  name:'Berned leno',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTRzJhDoiMq8tzh1sB6Aqj69Kxuw6DVHaq2Q&usqp=CAU',
                  nationality:{
                      country:'Germany',
                      nationality:'German',
                      logo:'',
                  },
              },
              {
                  jerseyNo:2,
                  name:'Ranar Alex Ranarsson',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTRzJhDoiMq8tzh1sB6Aqj69Kxuw6DVHaq2Q&usqp=CAU',
                  nationality:{
                      country:'iceland',
                      nationality:'icelandic',
                      logo:'',
                  },
              },
            ]
          },
          {
            id:7,
            meta:{
              name:'Arseenal',
              stadium:'Emirates',
            },
            images:{
              creast:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREm0av64pRH7cQZZp7fLC72NBK_bZ5YiGWNg&usqp=CAU',
              stadium:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAZw_dym6Esc6FYlLtJbUXARUTYd4N3OX4xw&usqp=CAU'
            },
            players:[
              {
                  jerseyNo:1,
                  name:'Berned leno',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTRzJhDoiMq8tzh1sB6Aqj69Kxuw6DVHaq2Q&usqp=CAU',
                  nationality:{
                      country:'Germany',
                      nationality:'German',
                      logo:'',
                  },
              },
              {
                  jerseyNo:2,
                  name:'Ranar Alex Ranarsson',
                  position:'Goalkeeper',
                  images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw0Kkp-R7ppm1qON9INEyiOUGsDqI4okLd6w&usqp=CAU',
                  nationality:{
                      country:'iceland',
                      nationality:'icelandic',
                      logo:'',
                  },
              },
            ]
          },
    ] 
}